# Generated by Django 4.2.6 on 2023-10-25 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0004_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 10, 25))),
                ('is_present', models.DateField(default='yes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmp.student')),
            ],
        ),
    ]
